### ISSUE TITLE
[ 1.17.B2] the sort order should start with the first episode by default not the last

### ISSUE THREAD

**Issue by TVZionDev** [TVZionDev/TVZionAndroidApp#14]
Reported: https://www.reddit.com/r/TVZionApp/comments/9mpxj8/tvzion_stable_relatively_beta_update/e7hjlff

Feature is pending where it loads the episodes in the last order you have used before. Ascending should be default. Will implement on next version.

**Comment by ediTv2** [comment]
Fixed in 1.17b.3
