### ISSUE TITLE
No selector on episodes

### ISSUE THREAD

**Issue by TVZionDev** [TVZionDev/TVZionAndroidApp#2]

**Comment by ediTv2** [comment]
Correct me if i'm wrong but this is likely a duplicate of #3

**Comment by TVZionDev** [comment]
It's not a dup. The first issue was on the show page about having no episode selector.Other issue was selector too thin on the home page on the media cards.

**Comment by TVZionDev** [comment]
Fixed on 1.17.BETA 2 release.
