### ISSUE TITLE
1.17b3. Single Source - Android TV

### ISSUE THREAD

**Issue by siaox** [TVZionDev/TVZionAndroidApp#25]
Loving the new changes but I'm only getting one source and then the search times out. Usually low quality. Any possibility of placing a minimum on quality for sources (1080p-720p)? Once again great work!

**Comment by ediTv2** [comment]
Have you tried searching under TVZion and Fmovies to see if the issue persists?

Also try increasing the number of link resolvers as that has worked for some users. (Found in settings)

**Comment by siaox** [comment]
Yeah I've increased the number of links but the search times out after finding the first link unfortunately. 

Same for FMovies.
